obj-$(CONFIG_OPPO_FINGERPRINT) += oppo_fp_common/

### Optical fingerprint sensor
obj-$(CONFIG_OPPO_FINGERPRINT_GOODIX_OPTICAL) += goodix_optical_fp/

### FEATURE MACRO
ccflags-$(CONFIG_OPPO_FINGERPRINT_NAVIGATION_ENABLE) += -DFP_NAVIGATION_ENABLE
